openapi: 3.0.0
info:
  title: Ticket Management API
  version: 1.0.0
  description: API for managing support tickets

paths:

  /tickets:
    post:
      summary: Create a new ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketCreate'
      responses:
        '201':
          description: Ticket created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Bad request
  
  /tickets/{ticketId}:
    get:
      summary: Get ticket
      description: Get resources associated with a specific ticket ID
      operationId: getTicket
      parameters:
        - name: ticketId
          in: path
          required: true
          description: Unique identifier of the ticket
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '404':
          description: Ticket not found
        '500':
          description: Internal server error

  /tickets/{ticketId}/status:
    put:
      summary: Update the status of a ticket
      parameters:
        - name: ticketId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketStatusUpdate'
      responses:
        '200':
          description: Ticket status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '404':
          description: Ticket not found

  /tickets/{ticketId}/comments:
    post:
      summary: Add a comment to a ticket
      parameters:
        - name: ticketId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentCreate'
      responses:
        '201':
          description: Comment added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Ticket not found

components:
  schemas:
    TicketCreate:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        priority:
          type: string
          enum: [low, medium, high]
          default: medium

    TicketStatusUpdate:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [open, in_progress, resolved, closed]

    CommentCreate:
      type: object
      required:
        - content
      properties:
        content:
          type: string

    Ticket:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [open, in_progress, resolved, closed]
        priority:
          type: string
          enum: [low, medium, high]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Comment:
      type: object
      properties:
        id:
          type: integer
        ticket_id:
          type: integer
        content:
          type: string
        created_at:
          type: string
          format: date-time