// Package ticketsservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package ticketsservice

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Tickets
	// (GET /tickets)
	ListTicket(ctx echo.Context, params ListTicketParams) error
	// Create a new Ticket
	// (POST /tickets)
	CreateTicket(ctx echo.Context) error
	// Deletes a Ticket by ID
	// (DELETE /tickets/{id})
	DeleteTicket(ctx echo.Context, id int) error
	// Find a Ticket by ID
	// (GET /tickets/{id})
	ReadTicket(ctx echo.Context, id int) error
	// Updates a Ticket
	// (PATCH /tickets/{id})
	UpdateTicket(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListTicket converts echo context to params.
func (w *ServerInterfaceWrapper) ListTicket(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "itemsPerPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "itemsPerPage", ctx.QueryParams(), &params.ItemsPerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemsPerPage: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTicket(ctx, params)
	return err
}

// CreateTicket converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTicket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTicket(ctx)
	return err
}

// DeleteTicket converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTicket(ctx, id)
	return err
}

// ReadTicket converts echo context to params.
func (w *ServerInterfaceWrapper) ReadTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReadTicket(ctx, id)
	return err
}

// UpdateTicket converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTicket(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/tickets", wrapper.ListTicket)
	router.POST(baseURL+"/tickets", wrapper.CreateTicket)
	router.DELETE(baseURL+"/tickets/:id", wrapper.DeleteTicket)
	router.GET(baseURL+"/tickets/:id", wrapper.ReadTicket)
	router.PATCH(baseURL+"/tickets/:id", wrapper.UpdateTicket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXT2/bxhP9Kov9/Y6spCTywbqldQsI6MFo01NgGGvuiJxU3GVmh1EEg9+9mF1RIiU6",
	"VWrAjd0cDC/J2fm3b98b3evcV7V34Djoxb0mCLV3AfYP89lMlrl3DI5laep6jblh9G76IXgn70JeQmVk",
	"VZOvgRiTh9xbkP+8rUEvNDqGAki3mQYiT2LTZjqw4Sb07AITukK3baYJPjZIYPXiffK2N7/JOnN/9wFy",
	"1q3YWwg5YS3ZxYCfzBqtQlc3nClr2KjdOx2dS4HzZ1wgQfAN5aCcZ7XyjevVdfmM68q9W60xZ3SF6moM",
	"XWkXzxqTjYPPNeQMVsWA0WVKNsZ7h/mfwKd5mxCwcAAjOWU6JzAM9tbEjStPlay0NQw/MFaS4oN77raj",
	"LtGOd6km9IQcN1lYmWYtkdZ+ozMNrqmkK+mpAotNpTNdYlH2enOIcejywZPzfBvYEIPteRy+RXdbky8I",
	"QtCZtt7BqHsuCYy9HVTS+4q8Hu9mU9uv7ma3Z7SbR6BBqSGF3/eg19h+4oOjHWQ2OMBB/HEUolv51Ok+",
	"Gt+VGBQGZZwyDXtVgAMSR+rt9VL1bFVlLCjfsPIrsf7ZsUqoVRZW6DA63HdVy/ff0/e310ud6U9AIcWc",
	"TV5NZtIzX4MzNeqFfjOZTd5IDwyXEQ9Tjtcgrot0HYaJ/4qBVborYaKjL4oEsLS7r7uLJE7JVMAgd/v9",
	"sZ9NaVjVpgDFXhE4CxQBphf6YwMkrXWmkorESGc9XqnQYSXwfJWd3JM2Ow6EDJXKfeP4EEnV8pf8joWU",
	"PeEa6PoktPmcQr++uMi+nMhNNlT111/JnjEHWfyfYKUX+n/Tw8gw3fHWdNfrdh/fEJntA4rVrLuTU2sM",
	"cdduzBgLsU9+2s0j0X5+rv082V+ea38p9hfn5iOGkcCbqjK0PQKm3AdTCOw6Wr8RBvVhBNA/xdsclFEO",
	"Nl1/jLOCkYCBg8KInMCeTAGnmE8O9qgXwoHAP3q7fYRaPrXqfFeXR6vLUwvLkaAk4LJXyYvuJ8fUQPtI",
	"PjqHhh5Ma1fZP6OcJ6OQdJMHTDDGJG22l8npPdo2IX0NDKfschXfB8UldNyyQS7j844pwKrl1SmtpJ3n",
	"ienySqaDQ4xO1kTWe6pmT0DR17YzFGw+Msj0iuoXpDYmqNQV+8KUpjtT053o3VYtr8Y1Z3SG+gWd/XtI",
	"RBEi4IacaNApQn4DY78tfDwho4wDbv9T/AXBTdByFtZqw3l5irY/opD04DoYbvLSuEII6gsTTvLwr0Pt",
	"+1z1n5mrzh13DocrAE5ev63JZ1fpC+OkY04ZHZPa9q8AAAD//4xebfLnFgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
