// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

import (
	"time"
)

// Defines values for TicketPriority.
const (
	TicketPriorityHigh   TicketPriority = "high"
	TicketPriorityLow    TicketPriority = "low"
	TicketPriorityMedium TicketPriority = "medium"
)

// Defines values for TicketStatus.
const (
	TicketStatusClosed     TicketStatus = "closed"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusOpen       TicketStatus = "open"
	TicketStatusResolved   TicketStatus = "resolved"
)

// Defines values for TicketCreatePriority.
const (
	TicketCreatePriorityHigh   TicketCreatePriority = "high"
	TicketCreatePriorityLow    TicketCreatePriority = "low"
	TicketCreatePriorityMedium TicketCreatePriority = "medium"
)

// Defines values for TicketStatusUpdateStatus.
const (
	TicketStatusUpdateStatusClosed     TicketStatusUpdateStatus = "closed"
	TicketStatusUpdateStatusInProgress TicketStatusUpdateStatus = "in_progress"
	TicketStatusUpdateStatusOpen       TicketStatusUpdateStatus = "open"
	TicketStatusUpdateStatusResolved   TicketStatusUpdateStatus = "resolved"
)

// Comment defines model for Comment.
type Comment struct {
	Content   *string    `json:"content,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	TicketId  *int       `json:"ticket_id,omitempty"`
}

// CommentCreate defines model for CommentCreate.
type CommentCreate struct {
	Content string `json:"content"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	CreatedAt   *time.Time      `json:"created_at,omitempty"`
	Description *string         `json:"description,omitempty"`
	Id          *int            `json:"id,omitempty"`
	Priority    *TicketPriority `json:"priority,omitempty"`
	Status      *TicketStatus   `json:"status,omitempty"`
	Title       *string         `json:"title,omitempty"`
	UpdatedAt   *time.Time      `json:"updated_at,omitempty"`
}

// TicketPriority defines model for Ticket.Priority.
type TicketPriority string

// TicketStatus defines model for Ticket.Status.
type TicketStatus string

// TicketCreate defines model for TicketCreate.
type TicketCreate struct {
	Description string                `json:"description"`
	Priority    *TicketCreatePriority `json:"priority,omitempty"`
	Title       string                `json:"title"`
}

// TicketCreatePriority defines model for TicketCreate.Priority.
type TicketCreatePriority string

// TicketStatusUpdate defines model for TicketStatusUpdate.
type TicketStatusUpdate struct {
	Status TicketStatusUpdateStatus `json:"status"`
}

// TicketStatusUpdateStatus defines model for TicketStatusUpdate.Status.
type TicketStatusUpdateStatus string

// PostTicketsJSONRequestBody defines body for PostTickets for application/json ContentType.
type PostTicketsJSONRequestBody = TicketCreate

// PostTicketsTicketIdCommentsJSONRequestBody defines body for PostTicketsTicketIdComments for application/json ContentType.
type PostTicketsTicketIdCommentsJSONRequestBody = CommentCreate

// PutTicketsTicketIdStatusJSONRequestBody defines body for PutTicketsTicketIdStatus for application/json ContentType.
type PutTicketsTicketIdStatusJSONRequestBody = TicketStatusUpdate
