// Package services provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package services

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	. "github.com/pleimer/ticketer/server/models"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Tickets
	// (GET /tickets)
	ListTicket(ctx echo.Context, params ListTicketParams) error
	// Create a new Ticket
	// (POST /tickets)
	CreateTicket(ctx echo.Context) error
	// Deletes a Ticket by ID
	// (DELETE /tickets/{id})
	DeleteTicket(ctx echo.Context, id int) error
	// Find a Ticket by ID
	// (GET /tickets/{id})
	ReadTicket(ctx echo.Context, id int) error
	// Updates a Ticket
	// (PATCH /tickets/{id})
	UpdateTicket(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListTicket converts echo context to params.
func (w *ServerInterfaceWrapper) ListTicket(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "itemsPerPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "itemsPerPage", ctx.QueryParams(), &params.ItemsPerPage)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemsPerPage: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTicket(ctx, params)
	return err
}

// CreateTicket converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTicket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTicket(ctx)
	return err
}

// DeleteTicket converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTicket(ctx, id)
	return err
}

// ReadTicket converts echo context to params.
func (w *ServerInterfaceWrapper) ReadTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReadTicket(ctx, id)
	return err
}

// UpdateTicket converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTicket(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/tickets", wrapper.ListTicket)
	router.POST(baseURL+"/tickets", wrapper.CreateTicket)
	router.DELETE(baseURL+"/tickets/:id", wrapper.DeleteTicket)
	router.GET(baseURL+"/tickets/:id", wrapper.ReadTicket)
	router.PATCH(baseURL+"/tickets/:id", wrapper.UpdateTicket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTW/bRhD9K4ttj4SlJPIhuqVVCwjowWjTU2AYa+6InFTcZWaHUQSD/72YXVGiRNpW",
	"kKaJgBwM8WM4n++9WT/o3Fe1d+A46PmDJgi1dwHizWw6lZ/cOwbHcmnqeo25YfRu8j54J89CXkJl5Kom",
	"XwMxpq9zb0F+eVuDnmt0DAWQbjMNRJ7Eps10YMNN6NkFJnSFbttME3xokMDq+bvkbW9+m3Xm/v495Kxb",
	"sbcQcsJasosBP5o1WoWubjhT1rBRu2eSxGw6u+DiCIJvKAflPKuVb9yuptcXXFPu3WqNOaMrVFdfkPDX",
	"F43DxsGnGnIGq2LA6DIlG+O9xfwf4GHeJgQsHMBITplGO16Sr8GBvbvfjn5VE3pCji8trEyzZj3Xa7/R",
	"mQbXVFJguqvAYlPpTJdYlL0yD74ODTt4cp7vAhtisD2Px0/R3dXkC4IQdKatdzDqnksCY5eL0ToYeQ3P",
	"zwolXrLtd2afe68hvYDjM0W38qnY/mzflhgUBmWcMg17VYADMjLqNzdL1bNVlbGgfMPKr8T6N8cqYUBZ",
	"WKHD6HBfmZb3f6X3b26WOtMfgUKKOb16cTXtZm1q1HP96mp69UrKMVzGkUw4gipeFwlcx4n/gYFVQl64",
	"St2hSKel3b3dwVKckqmAQZjy7tTPpjSsalOAYq8InAWKM9Zz/aEBksY6U0lFYqSzHksrdFgJQl5kAyC3",
	"2WkgZKhU7hvHh0iqlr/kdyykfBNugG4Goc2nFPrl9XX2dCK32fFOfPmZWhRzkIufCVZ6rn+aHBbuZKcC",
	"k12v2318Q2S2j+h+s+4mp9YYOOn+9LEQ++QnYnTYe8/Zznr75Dnb1z2RftpWjKL8NVVlaHsCRMG/KQRm",
	"nSjeimj5MALgXwkMQ1BGOdh0/TDOCiYCBg4KI1ICezIFDDGeHOxRLroBgX/xdvsFu+ZJzf6hzT1t/o9k",
	"+USOEwzYqzxOV/djMjXQfiGbzyHxo2mlnOznE/arkzBx4YhLY1xss/1imTygbRPA1sAw5OciPg+KS+jY",
	"uUEu4/2Oa2DVcjEkZvryvPWzXMg+PcToFoEswt4esAMg9LfBGZo/G1n9vaL6BamNCSp1xV64NnczNN0E",
	"77dquRhX6dFTxu/o7PMQiLJNwA05Ue0hIv4EY78vPPyPqjEOsN6/fBcLL0HHWdiqDeflEF1/19YcwfNo",
	"/eelcYUI0BNngOThm0Prx8nja588zj05HHoquGkiPL6vQ0TK6dKpf0rd0dNG2/4bAAD//4uviJmeFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
