// Package messagesservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package messagesservice

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Thread Messages
	// (GET /threads/{threadId})
	ListThreadMessages(ctx echo.Context, threadId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListThreadMessages converts echo context to params.
func (w *ServerInterfaceWrapper) ListThreadMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "threadId" -------------
	var threadId string

	err = runtime.BindStyledParameterWithOptions("simple", "threadId", ctx.Param("threadId"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter threadId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListThreadMessages(ctx, threadId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/threads/:threadId", wrapper.ListThreadMessages)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6yUzW7bMAzHX8XgdjQSb7v5lmGXABtQbL0NQ6HKdMzC+hhFF/ACv/sg2U7TRgF6yE0S",
	"KfLHPykdQTvjnUUrAeojBN2hUWm5E1G6M2gl7jw7jyyEyaadlcUgo0eoIQiTPcBUrraH2ZBxaKlHq0ze",
	"SE32ONC/c3+yggdkmKZyPXKPT6gl+v7AENQBL6nVqaK0JUGTFh8ZW6jhw/ZFi+0ixPZMhZdcilmNcf/o",
	"mjEvgn53hjvFQpq8yqdolGQrL6F1fYP8upQLkLfhWnbmVmhXerV0Imdi9P34IO5WBMGS95jPFUQx4zni",
	"o3M9KpuMw3VI6RhV83ClutvBDzbmyfHlpvo82MVko1HUZ3GvPLTLDFEU1AOTjL8i/xz4KypG3g3SnX6H",
	"RJqO4RSkE/EwxRhk2yRQg0EzeSFnoYbd3b5oHReMwoTPZA/FrHIR/dmo5FeCkPQx3vKEQ7G720MJz8hh",
	"DlRtPm2qNGQerfIENXzZVJsKSvBKusS8nUOH7XFe7JspHh/mOXkN9nMGwsKsGckWwaOmlvTCCCkbJ8Z9",
	"AzV8pyD3ybRypvSsDEp6kL/fprnvsJhvFPtvEFWCOgHD2iFYWSG+kr8DpdEVHrBcPuVcF/9E5+CdDXO7",
	"PlfVm+9Zed+TTuzbpxBhjmfx3jXG6396McKx36/rZAxDL0W8Ea8UPYVltAZjFI+LeKsWJ/mmaZr+BwAA",
	"//8wO+9CiwYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
