// Package messagesservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package messagesservice

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// reply to thread
	// (POST /threads/reply)
	ReplyToThread(ctx echo.Context) error
	// List Thread Messages
	// (GET /threads/{threadId})
	ListThreadMessages(ctx echo.Context, threadId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ReplyToThread converts echo context to params.
func (w *ServerInterfaceWrapper) ReplyToThread(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReplyToThread(ctx)
	return err
}

// ListThreadMessages converts echo context to params.
func (w *ServerInterfaceWrapper) ListThreadMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "threadId" -------------
	var threadId string

	err = runtime.BindStyledParameterWithOptions("simple", "threadId", ctx.Param("threadId"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter threadId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListThreadMessages(ctx, threadId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/threads/reply", wrapper.ReplyToThread)
	router.GET(baseURL+"/threads/:threadId", wrapper.ListThreadMessages)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUTW/bMAz9KwK3o5Fk2823FLsE2ICi620YCtWmYxa2pFF0gazwfx8k26kby0WH9eQP",
	"UuTje098gsK2zho04iF/Al/U2Or4uhfRRd2ikfDl2DpkIYyxwhoZA3JyCDl4YTJH6LMpdjcEEgkVNWh0",
	"mw5Smfzt6c88n4zgERn6Ppt+2fsHLCTkfkfv9RGXqPV5ovhJgm18+chYQQ4fts9cbEcitjMWnntpZn0K",
	"3/e2PKVJKN7c4VqzUEFOp1uUWpKTZ1DZpkR+OcoCyGW5im37XtBWtBqVSIUYXXO6E/teCLwh5zDdy4tm",
	"xjnEe2sb1CYGu3WQUjPq8m5luvcD35nQJ4Uv5ep5sYWzsdXUJOGuXLRlh0AKFh2TnH4E/EPhK9SMvO+k",
	"Pm+HiDT+hnORWsRBH2qQqSJBJfqCyQlZAznsrw+qsqwYhQkfyRzVwLIK+dzqmJeBkDSh3niFvdpfHyCD",
	"R2Q/FNptPm120WQOjXYEOXzZ7DY7yMBpqSPm7VDab6PbIlnWyxJUDCuxSjeN6jyyV2SUHpFB7MER2aGE",
	"HG5C+q29naKMvzv0cjWugNlK1M41VMST2wcfek2Ldanc6gZ5zYUJ9cKmeDHdSGGYL4wfnuNg8R56Z40f",
	"IHze7f5pgNcsP+3eVwAFNFgOhuvaVvNprsWEsc+edXwaXg5lH9ofMaHlzWAsVO3kHDLKOyyoomJN0W/k",
	"ZZBz8lu0EesWJS7Wn5dtbmtUwwl1+ArB7ZBH48F002DCOjqE4goS7jCbUXip56//lORN6+iszeUqWmrF",
	"6LtGVDgRNWvIy4VigbyJizN9fd/3fwMAAP//xpEw41MIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
