// Package messagesservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package messagesservice

// Attachment defines model for Attachment.
type Attachment struct {
	Content     *string `json:"content,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	Filename    *string `json:"filename,omitempty"`
	Id          *string `json:"id,omitempty"`
	Size        *int    `json:"size,omitempty"`
}

// Message defines model for Message.
type Message struct {
	Attachments *[]Attachment  `json:"attachments,omitempty"`
	Body        *string        `json:"body,omitempty"`
	Cc          *[]Participant `json:"cc,omitempty"`
	Date        *int           `json:"date,omitempty"`
	Folders     *[]string      `json:"folders,omitempty"`
	From        *[]Participant `json:"from,omitempty"`
	Id          *string        `json:"id,omitempty"`
	Object      *string        `json:"object,omitempty"`
	ReplyTo     *[]Participant `json:"reply_to,omitempty"`
	Snippet     *string        `json:"snippet,omitempty"`
	Starred     *bool          `json:"starred,omitempty"`
	Subject     *string        `json:"subject,omitempty"`
	ThreadId    *string        `json:"thread_id,omitempty"`
	To          *[]Participant `json:"to,omitempty"`
	Unread      *bool          `json:"unread,omitempty"`
}

// Participant defines model for Participant.
type Participant struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// ReplyToThreadJSONBody defines parameters for ReplyToThread.
type ReplyToThreadJSONBody struct {
	Body     *string `json:"body,omitempty"`
	ThreadId *string `json:"thread_id,omitempty"`
}

// ReplyToThreadJSONRequestBody defines body for ReplyToThread for application/json ContentType.
type ReplyToThreadJSONRequestBody ReplyToThreadJSONBody
